github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/microsoft-openjdk
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/microsoft-openjdk-dependency:main
  with:
    type:    jdk
    version: "11"
- name:            JRE 11
  id:              jre
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/microsoft-openjdk-dependency:main
  with:
    type:    jre
    version: "11"
- name:            JDK 16
  id:              jdk
  version_pattern: "16\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/microsoft-openjdk-dependency:main
  with:
    type:    jdk
    version: "16"
- name:            JRE 16
  id:              jre
  version_pattern: "16\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/microsoft-openjdk-dependency:main
  with:
    type:    jre
    version: "16"
- id:   jvmkill
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    owner:      cloudfoundry
    repository: jvmkill
    token:      ${{ secrets.JAVA_GITHUB_TOKEN }}
