# Copyright 2018-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.6"

[buildpack]
id       = "paketo-buildpacks/microsoft-openjdk"
name     = "Paketo Microsoft OpenJDK Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/paketo-buildpacks/microsoft-openjdk"
description = "A Cloud Native Buildpack that provides the Microsoft OpenJDK implementations of JREs and JDKs"
keywords    = ["java", "jvm", "jre", "jdk"]

[[buildpack.licenses]]
type = "Apache-2.0"
uri  = "https://github.com/paketo-buildpacks/microsoft-openjdk/blob/main/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "io.paketo.stacks.tiny"

[[stacks]]
id = "*"

[[metadata.configurations]]
name        = "BPL_JVM_HEAD_ROOM"
description = "the headroom in memory calculation"
default     = "0"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_LOADED_CLASS_COUNT"
description = "the number of loaded classes in memory calculation"
default     = "35% of classes"
launch      = true

[[metadata.configurations]]
name        = "BPL_JVM_THREAD_COUNT"
description = "the number of threads in memory calculation"
default     = "250"
launch      = true

[[metadata.configurations]]
name        = "BPL_HEAP_DUMP_PATH"
description = "write heap dumps on error to this path"
default     = ""
launch      = true

[[metadata.configurations]]
name        = "BP_JVM_VERSION"
description = "the Java version"
default     = "11"
build       = true

[[metadata.configurations]]
name        = "BP_JVM_TYPE"
description = "the JVM type - JDK or JRE"
default     = "JRE"
build       = true

[[metadata.configurations]]
name        = "JAVA_TOOL_OPTIONS"
description = "the JVM launch flags"
launch      = true

[[metadata.dependencies]]
id      = "jdk"
name    = "Adoptium JDK"
version = "8.0.302"
uri     = "https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz"
sha256  = "cc13f274becf9dd5517b6be583632819dfd4dd81e524b5c1b4f406bdaf0e063a"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "Microsoft OpenJDK"
version = "11.0.12"
uri     = "https://aka.ms/download-jdk/microsoft-jdk-11.0.12.7.1-linux-x64.tar.gz"
sha256  = "9520bb8a603f9859dc760fde3fecff1de06ecf1f1b7808f270f4e42ac4766a0e"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[[metadata.dependencies]]
id      = "jdk"
name    = "Microsoft OpenJDK"
version = "16.0.2"
uri     = "https://aka.ms/download-jdk/microsoft-jdk-16.0.2.7.1-linux-x64.tar.gz"
sha256  = "30924e429fa7b138b3ce4d15c07a2c0284752363e4ceb56a479d244472a0ceb8"
stacks  = [ "io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*" ]

  [[metadata.dependencies.licenses]]
  type = "GPL-2.0 WITH Classpath-exception-2.0"
  uri  = "https://openjdk.java.net/legal/gplv2+ce.html"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/helper",
  "bin/main",
  "buildpack.toml",
]
